services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      target: builder
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8000
      - VITE_DOCKER_MODE=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_URL=http://ollama:11434
      #- CHROMA_DB_PATH=/app/data/chroma_db
    volumes:
      - ./backend:/app
      #- ./backend/data/chroma_db:/app/data/chroma_db
    env_file:
        - ./backend/.env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  ollama:
    build:
      context: ./LLM
      dockerfile: dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama

volumes:
  ollama_volume:
  chroma_volume:
