import { defineStore } from 'pinia'
import { ref, computed } from 'vue'
import * as api from '@/api/timelineAPI'
import type { TimelineEventOut, EventType } from '@/api/timelineAPI'

/**
 * Timeline store – manages session timeline events: fetching, generating,
 * filtering, and deleting.
 */
export const useTimelineStore = defineStore('timeline', () => {
  /** Cached list of timeline events. */
  const events = ref<TimelineEventOut[]>([])
  /** Whether events are being fetched. */
  const loading = ref(false)
  /** Whether events are being generated by the backend. */
  const generating = ref(false)
  /** Last error message, if any. */
  const error = ref<string | null>(null)

  /** Total number of events currently in the store. */
  const eventCount = computed(() => events.value.length)

  /** Events grouped by their event type key. */
  const eventsByType = computed(() => {
    const grouped: Record<EventType, TimelineEventOut[]> = {
      combat: [],
      discovery: [],
      dialogue: [],
      travel: [],
      rest: [],
      quest: [],
      other: [],
    }
    for (const event of events.value) {
      const type = event.event_type as EventType
      if (grouped[type]) {
        grouped[type].push(event)
      } else {
        grouped.other.push(event)
      }
    }
    return grouped
  })

  /**
   * Fetch timeline events for the given session from the backend.
   * @param sessionId - Session identifier (defaults to 'default').
   */
  async function fetchEvents(sessionId = 'default') {
    loading.value = true
    error.value = null
    try {
      const response = await api.listEvents(sessionId)
      events.value = response?.events ?? []
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to load events'
      events.value = []
    } finally {
      loading.value = false
    }
  }

  /**
   * Request the backend to generate timeline events from session data.
   * @param sessionId - Session identifier.
   * @returns The generate response or null on failure.
   */
  async function generateEvents(sessionId = 'default') {
    if (generating.value) return
    generating.value = true
    error.value = null
    try {
      const response = await api.generateEvents(sessionId)
      events.value = response?.events ?? []
      return response
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to generate events'
      return null
    } finally {
      generating.value = false
    }
  }

  /**
   * Remove a single event by its ID from both the backend and local store.
   * @param eventId - The event's unique identifier.
   */
  async function removeEvent(eventId: string) {
    try {
      await api.deleteEvent(eventId)
      events.value = events.value.filter((e) => e.id !== eventId)
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to delete event'
    }
  }

  /**
   * Clear all events for a session on the backend and in the local store.
   * @param sessionId - Session identifier.
   */
  async function clearEvents(sessionId = 'default') {
    try {
      await api.clearSessionEvents(sessionId)
      events.value = []
    } catch (err) {
      error.value = err instanceof Error ? err.message : 'Failed to clear events'
    }
  }

  return {
    events,
    loading,
    generating,
    error,
    eventCount,
    eventsByType,
    fetchEvents,
    generateEvents,
    removeEvent,
    clearEvents,
  }
})
