"""Pydantic models for LLM request/response schemas."""

from uuid import UUID

from pydantic import BaseModel, Field


class LLMRequest(BaseModel):
    """Request model for querying the custom LLM model.

    Attributes:
        player_id: The ID of the player making the request.
        input_string: The text prompt for the LLM.
        use_rulebook: Whether to include rulebook context in the response.
    """

    player_id: UUID = Field(..., description='ID aus /players')
    input_string: str = Field(..., description='Text prompt for the custom model')
    use_rulebook: bool = Field(False, description='Whether to consult the rulebook for the answer')


class LLMResponse(BaseModel):
    """Response model containing text generated by the LLM."""

    output: str = Field(..., description='Text generated by the custom model')
